### ISSUE TITLE
Matplotlib version issue

### ISSUE THREAD

**Issue by hb1500** [probcomp/trcrpm#2]
Hi, 

I installed the package in my env. I found that there is a version conflict on matplotlib. When I am plot ing the time series with matplotlib, I got this error: `AttributeError: 'module' object has no attribute 'to_rgba', which is due to the old version. When i am installing the package, it requires matplotlib version 1.5.1-np111py27_0. This version throws me the to_rgba error. Could you specify which version of matplotlib works best?

**Comment by fsaad** [comment]
Hi @hb1500 did you install the package in a conda environment or in a python virtualenvironment?

**Comment by hb1500** [comment]
Yes, I did. I also tried to update my matplotlib verision, then restart kernel when using ipython notebook.

**Comment by fsaad** [comment]
@hb1500 Thanks, the issue seems to be that the version of `jupyter` in the [`meta.yaml`](https://github.com/probcomp/trcrpm/blob/master/conda/meta.yaml#L20) file is not specified so it's probably using the latest which is incompatible with matplotlib 1.5. I'll search for the right version and provide an update.

**Comment by hb1500** [comment]
@fsaad FYI: 
I attempted to install a newer version of matplolib == 2.2.3. This is the warning I got which involves the package conflicts. 

UnsatisfiableError: The following specifications were found to be in conflict:
  - matplotlib=2.2.3
  - trcrpm -> cgpm -> matplotlib=1.5 -> freetype=2.5 -> libpng==1.5.13
  - trcrpm -> cgpm -> matplotlib=1.5 -> pyqt=4 -> qt[version='>=4.8.6,<5.0']
  - trcrpm -> cgpm -> matplotlib=1.5 -> pyqt=4 -> sip==4.18

Thanks for help!

**Comment by fsaad** [comment]
@hb1500 I think the following commit provides the fix
https://github.com/probcomp/trcrpm/commit/9cfa82f280ed7292f1832a3deb8e92a4aad5b799

I'm working on creating a new release on Conda cloud so that it's all automatic.

In the meantime you could try `conda install ipykernel=4.8.2` in your environment. Let me know if that works (if not, please hold tight until I create the patched release on Conda cloud). Thanks!

**Comment by hb1500** [comment]
@fsaad As you suggested, installing ipykernel=4.8.2 solves the issue! Thank you very much for the help! I will close this issue :)
